from pydantic import BaseModel

class CustomerData(BaseModel):
    EXT_SOURCE_2                             : float
    EXT_SOURCE_3                             : float
    NAME_EDUCATION_TYPE                       : int
    CODE_GENDER_0_0                           : int
    FLAG_DOCUMENT_3                           : int
    NAME_CONTRACT_STATUS_most_use_Refused     : int
    NAME_INCOME_TYPE                          : int
    CNT_DRAWINGS_ATM_CURRENT_mean            : float
    EXT_SOURCE_1                             : float
    FLAG_OWN_CAR_0_0                          : int
    PAYMENT_RATIO_mean                       : float
    MONTHS_BALANCE_std                       : float
    CNT_PAYMENT_max                          : float
    BALANCE_LIMIT_RATIO_max                  : float
    DAYS_BIRTH                                : int
    SK_ID_PREV_nunique                       : float
    NAME_FAMILY_STATUS_Married                : int
    CNT_DRAWINGS_CURRENT_mean                : float
    AMT_DOWN_PAYMENT_max                     : float
    FLAG_DOCUMENT_6                           : int
    NAME_YIELD_GROUP_most_use                 : int
    REGION_RATING_CLIENT                      : int
    DEF_30_CNT_SOCIAL_CIRCLE                 : float
    WALLSMATERIAL_MODE_Panel                  : int
    DAYS_LATE_max                            : float
    REG_CITY_NOT_LIVE_CITY                                    : int
    DAYS_EMPLOYED                                             : int
    SK_DPD_DEF_max                                           : float
    NAME_CONTRACT_TYPE_most_use_Cash_loans                    : int
    AMT_INSTALMENT_sum                                       : float
    CODE_REJECT_REASON_most_use_HC                            : int
    NAME_GOODS_CATEGORY_most_use_Clothing_and_Accessories     : int
    OCCUPATION_TYPE_Core_staff                                : int
    ORGANIZATION_TYPE_Transport_type_3                        : int
    AMT_CREDIT                                               : float
    OWN_CAR_AGE                                              : float
    CODE_REJECT_REASON_most_use_SCOFR                         : int
    NAME_CONTRACT_TYPE_Cash_loans                             : int
    CNT_INSTALMENT_FUTURE_max                                : float
    NAME_GOODS_CATEGORY_most_use_Furniture                    : int
    DRAWINGS_LIMIT_RATIO_mean                                : float
    AMT_ANNUITY                                              : float
    DAYS_LAST_DUE_1ST_VERSION_max                            : float
    DAYS_DECISION_min                                        : float
    AMT_DIFF_mean                                            : float
    AMT_DRAWINGS_ATM_CURRENT_mean                            : float
    NUM_INSTALMENT_NUMBER_max                                : float
    FLOORSMAX_AVG                                            : float
    NAME_TYPE_SUITE_most_use_Other_A                          : int
    PRODUCT_COMBINATION_most_use_Card_Street                  : int
    ORGANIZATION_TYPE_Self_employed                           : int
    AMT_REQ_CREDIT_BUREAU_QRT                                : float
    SK_DPD_min                                               : float
    MONTHS_BALANCE_max                                       : float
    EMERGENCYSTATE_MODE_0_0                                   : int
    AMT_BALANCE_max                                          : float
    DAYS_ID_PUBLISH                                           : int
    DAYS_FIRST_DUE_min                                       : float
    ORGANIZATION_TYPE_Postal                                  : int
    FLAG_DOCUMENT_18                                          : int
    DAYS_LAST_DUE_mean                                       : float
    DAYS_DECISION_mean                                       : float
    NAME_SELLER_INDUSTRY_most_use_Industry                    : int
    OCCUPATION_TYPE_Laborers                                  : int
    NAME_CLIENT_TYPE_most_use_Repeater                        : int
    NAME_CLIENT_TYPE_most_use_Refreshed                       : int
    ORGANIZATION_TYPE_Industry_type_3                         : int
    NAME_TYPE_SUITE_Unaccompanied                             : int
    ORGANIZATION_TYPE_Construction                            : int
    ORGANIZATION_TYPE_Other                                   : int
    CHANNEL_TYPE_most_use_AP_Cash_loan                        : int
    CHANNEL_TYPE_most_use_Channel_of_corporate_sales          : int
    PRODUCT_COMBINATION_most_use_POS_mobile_with_interest     : int
    OCCUPATION_TYPE_Drivers                                   : int
    AMT_ANNUITY_min                                          : float
    RATE_DOWN_PAYMENT_max                           : float
    HOUSETYPE_MODE_specific_housing                  : int
    AMT_REQ_CREDIT_BUREAU_MON                       : float
    LIVE_REGION_NOT_WORK_REGION                      : int
    SK_DPD_max                                      : float
    AMT_REQ_CREDIT_BUREAU_WEEK                      : float
    AMT_CREDIT_LIMIT_ACTUAL_max                     : float
    ORGANIZATION_TYPE_Industry_type_9                : int
    FLAG_DOCUMENT_16                                 : int
    NAME_FAMILY_STATUS_Single_not_married            : int
    CHANNEL_TYPE_most_use_Country_wide               : int
    CNT_INSTALMENT_FUTURE_min                       : float
    OCCUPATION_TYPE_Low_skill_Laborers               : int
    FLAG_WORK_PHONE                                  : int
    DAYS_LAST_DUE_max                               : float
    DAYS_LAST_PHONE_CHANGE                          : float
    ORGANIZATION_TYPE_Government                     : int
    NAME_TYPE_SUITE_Other_B                          : int
    ORGANIZATION_TYPE_Military                       : int
    PRODUCT_COMBINATION_most_use_Cash_Street_low     : int
    YEARS_BEGINEXPLUATATION_AVG                     : float
    CNT_PAYMENT_min                                 : float
    SELLERPLACE_AREA_max                            : float
    AMT_DIFF_max                                    : float
    NAME_SELLER_INDUSTRY_most_use_Construction       : int
    DAYS_FIRST_DRAWING_mean                                    : float
    HOUR_APPR_PROCESS_START_max                                : float
    LIVE_CITY_NOT_WORK_CITY                                     : int
    NAME_HOUSING_TYPE_Rented_apartment                          : int
    PRODUCT_COMBINATION_most_use_Cash_Street_high               : int
    ORGANIZATION_TYPE_Business_Entity_Type_3                    : int
    NAME_CONTRACT_TYPE_most_use_Revolving_loans                 : int
    ORGANIZATION_TYPE_School                                    : int
    ORGANIZATION_TYPE_Kindergarten                              : int
    DAYS_LAST_DUE_min                                          : float
    CNT_DRAWINGS_CURRENT_sum                                   : float
    OCCUPATION_TYPE_Accountants                                 : int
    BASEMENTAREA_AVG                                           : float
    NAME_HOUSING_TYPE_Municipal_apartment                       : int
    OCCUPATION_TYPE_Security_staff                              : int
    CHANNEL_TYPE_most_use_Contact_center                        : int
    AMT_INSTALMENT_mean                                        : float
    ORGANIZATION_TYPE_Trade_type_2                              : int
    AMT_PAYMENT_CURRENT_max                                    : float
    EMERGENCYSTATE_MODE_1_0                                     : int
    ORGANIZATION_TYPE_Transport_type_2                          : int
    AMT_REQ_CREDIT_BUREAU_YEAR                                 : float
    PRODUCT_COMBINATION_most_use_POS_industry_with_interest     : int
    FLAG_DOCUMENT_11                                            : int
    AMT_REQ_CREDIT_BUREAU_DAY                                  : float
    AMT_DIFF_min                                       : float
    AMT_DRAWINGS_POS_CURRENT_mean                      : float
    SK_ID_PREV_count                                   : float
    NAME_CONTRACT_STATUS_most_use_Active                : int
    AMT_DRAWINGS_ATM_CURRENT_sum                       : float
    ENTRANCES_AVG                                      : float
    DAYS_REGISTRATION                                  : float
    NAME_PRODUCT_TYPE_most_use_x_sell                   : int
    NAME_FAMILY_STATUS_Civil_marriage                   : int
    ORGANIZATION_TYPE_Security_Ministries               : int
    DAYS_LATE_mean                                     : float
    ORGANIZATION_TYPE_Bank                              : int
    ORGANIZATION_TYPE_Business_Entity_Type_2            : int
    SELLERPLACE_AREA_mean                              : float
    NONLIVINGAREA_AVG                                  : float
    CNT_DRAWINGS_ATM_CURRENT_sum                       : float
    NAME_HOUSING_TYPE_House_apartment                   : int
    PRODUCT_COMBINATION_most_use_Cash_X_Sell_middle     : int
    AMT_INCOME_TOTAL                                   : float
    NAME_FAMILY_STATUS_Separated                        : int
    ORGANIZATION_TYPE_Legal_Services                    : int
    ORGANIZATION_TYPE_Realtor                           : int
    REGION_POPULATION_RELATIVE                         : float
    NAME_TYPE_SUITE_Spouse_partner                      : int
    ORGANIZATION_TYPE_Industry_type_11                  : int
    ORGANIZATION_TYPE_Trade_type_6                                 : int
    ORGANIZATION_TYPE_Trade_type_7                                 : int
    ORGANIZATION_TYPE_Restaurant                                   : int
    WALLSMATERIAL_MODE_Block                                       : int
    AMT_GOODS_PRICE_min                                           : float
    PRODUCT_COMBINATION_most_use_Card_X_Sell                       : int
    DAYS_DECISION_max                                             : float
    FLAG_DOCUMENT_13                                               : int
    FLOORSMIN_AVG                                                 : float
    ORGANIZATION_TYPE_Industry_type_12                             : int
    NAME_HOUSING_TYPE_With_parents                                 : int
    PRODUCT_COMBINATION_most_use_POS_industry_without_interest     : int
    AMT_DRAWINGS_CURRENT_sum                                      : float
    AMT_ANNUITY_max                                               : float
    NONLIVINGAPARTMENTS_AVG                                       : float
    NAME_CONTRACT_STATUS_most_use_Signed                           : int
    APARTMENTS_AVG                                                : float
    HOUR_APPR_PROCESS_START_std                                   : float
    AMT_APPLICATION_mean                                          : float
    CNT_CHILDREN                                                   : int
    NAME_CASH_LOAN_PURPOSE_most_use_Buying_a_holiday_home_land     : int
    DAYS_LATE_min                                                 : float
    OCCUPATION_TYPE_High_skill_tech_staff                          : int
    OCCUPATION_TYPE_Cleaning_staff                                 : int
    OBS_30_CNT_SOCIAL_CIRCLE                                      : float
    NAME_PORTFOLIO_most_use_Cash                      : int
    NAME_HOUSING_TYPE_Office_apartment                : int
    NAME_SELLER_INDUSTRY_most_use_Auto_technology     : int
    HOUR_APPR_PROCESS_START                           : int
    CHANNEL_TYPE_most_use_Stone                       : int
    NAME_TYPE_SUITE_most_use_Unaccompanied            : int
    CHANNEL_TYPE_most_use_Credit_and_cash_offices     : int
    COMMONAREA_AVG                                   : float
    WALLSMATERIAL_MODE_Stone_brick                    : int
    DAYS_FIRST_DRAWING_max                           : float
    ORGANIZATION_TYPE_Trade_type_3                    : int
    AMT_DRAWINGS_CURRENT_mean                        : float
