name: Python CI

on:
  push:
    branches: [ "main_doker" ]
  pull_request:
    branches: [ "main_docker" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry to not create virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --without dev

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/ --maxfail=1 --disable-warnings -q



        